# Generated by Django 5.1 on 2026-03-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('ceo', models.CharField(max_length=30)),
            ],
        ),
    ]
